# Generated by Django 4.0.4 on 2022-07-13 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_alter_marca_options_alter_producto_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marca',
            options={'ordering': ['marca'], 'verbose_name': 'marca', 'verbose_name_plural': 'marcas'},
        ),
    ]
